# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'tweet-sentiment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chuck
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 4.10'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'Moya/RxSwift', '~> 12.0'
  pod 'Swinject', '2.5.0'
  pod 'SwinjectAutoregistration', '2.5.0'
  
  #target 'Domain' do
  #  pod 'RxSwift', '~> 4.0'
  #end
end
